spring:
  datasource:
    hikari:
      maximum-pool-size: ${DB_HIKARI_POOL_SIZE}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      platform: ${DB_SQL_DIALECT}
  jpa:
    properties:
      jakarta:
        persistence:
          query:
            timeout: ${DB_QUERY_TIMEOUT}
    show-sql: ${DB_SHOW_SQL}
  task:
    scheduling:
      pool:
        size: ${TASK_SHEDULER_POOL_SIZE:1}
task:
  executor:
    pool:
      core-size: ${TASK_EXECUTOR_POOL_SIZE:8}
      max-size: ${TASK_EXECUTOR_POOL_MAX:16}
      keep-alive: ${TASK_EXECUTOR_ALIVE:120}
s3:
  bucket: ${S3_BUCKET}
  folder: ${S3_FOLDER}
  key: ${S3_KEY}
  secret: ${S3_SECRET}
  url: ${S3_URL}
  contenttype: ${S3_CONTENT_TYPE}